URL = http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1_osx-cocoa-x86-64.pkg
DOWNLOADED = wkhtmltox.pkg
BINARY = $(TMPDIR)/bin/wkhtmltopdf

pkg_content = $(TMPDIR)/content
payload = $(pkg_content)/Payload
app_tar_xz = $(TMPDIR)/usr/local/share/wkhtmltox-installer/app.tar.xz

unpack: tmp $(DOWNLOADED)
	pkgutil --expand $(DOWNLOADED) $(pkg_content)
	tar -xf $(payload) -C $(TMPDIR)
	tar -xzf $(app_tar_xz) -C $(TMPDIR)

